import app from "./locale-layout.js";

const TEAM_STYLE = String.raw`
<style id="unit369-ai-team-style">
.role-strip{display:grid;grid-template-columns:repeat(4,1fr);gap:7px;margin:0 0 14px}.role-chip{min-width:0;padding:9px 8px;border:1px solid #1d3045;border-radius:11px;background:#08111b}.role-name{font-size:10px;font-weight:800;color:#dce9f7;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.role-desc{font-size:8.5px;color:#697d96;margin-top:3px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.team-sessionbar{display:flex;gap:7px;align-items:center;margin:0 0 10px}.team-session-title{flex:1;min-width:0;color:#8297b0;font-size:10px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.team-drawer{display:none;border:1px solid #1d3045;border-radius:13px;background:#07101a;padding:10px;margin:0 0 12px;max-height:290px;overflow:auto}.team-drawer.open{display:block}.team-session{display:flex;gap:7px;align-items:center;padding:9px 3px;border-bottom:1px solid #142337}.team-session:last-child{border-bottom:0}.team-session-main{flex:1;min-width:0}.team-session-q{font-size:11px;color:#d8e6f6;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.team-session-meta{font-size:9px;color:#647890;margin-top:2px}.team-mini{border:1px solid #23405c;background:#0a1420;color:#77ceff;border-radius:8px;padding:6px 8px;font-size:9px;font-weight:700}.team-final{margin-top:14px;border:1px solid #27557b;border-radius:15px;background:linear-gradient(180deg,#0b1b2b,#08131f);overflow:hidden}.team-final-head{padding:12px 14px;font-size:12px;font-weight:850;color:#65caff;border-bottom:1px solid #1a3650}.team-final-body{padding:13px}.team-section{padding:9px 0;border-bottom:1px solid #142a40}.team-section:last-child{border-bottom:0}.team-section h4{margin:0 0 5px;font-size:10px;color:#70bfff;text-transform:uppercase;letter-spacing:.08em}.team-section div{font-size:13px;line-height:1.55;color:#dce7f4;white-space:pre-wrap}.team-actions{display:flex;flex-wrap:wrap;gap:7px;margin-top:9px}.provider-state{font-size:8px;margin-left:auto;padding:3px 6px;border-radius:999px;background:#102238;color:#69bfff}.provider-state.off{background:#26151b;color:#ff8392}.panel-head{gap:7px}.panel .roleline{font-size:9px;color:#6f8298;padding:8px 13px 0}.team-empty{padding:16px;text-align:center;color:#667b93;font-size:11px}
html[dir="rtl"] .team-session,html[dir="rtl"] .team-sessionbar{flex-direction:row-reverse}.locale-long .role-strip{grid-template-columns:repeat(2,1fr)}
@media(max-width:390px){.role-strip{grid-template-columns:repeat(2,1fr)}}
</style>`;

function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}})}

async function synthesize(request,env){
  try{
    const body=await request.json();
    const question=String(body.question||"").trim();
    const answers=body.answers&&typeof body.answers==="object"?body.answers:{};
    const usable=Object.entries(answers).filter(([,v])=>typeof v==="string"&&v.trim());
    if(!question||usable.length<2)return json({error:"At least two model answers are required."},400);
    const prompt=`You are the Unit369 lead synthesizer. The user asked:\n${question}\n\nIndependent team answers:\n${usable.map(([k,v])=>`[${k}]\n${v}`).join("\n\n")}\n\nReturn ONLY valid JSON with exactly these string keys: summary, consensus, disagreements, risks, recommendation, next_steps. Be decisive, concrete, concise, preserve important uncertainty, and answer in the SAME language as the user's question. Do not praise or rank models by brand.`;
    if(env.AI){
      const result=await env.AI.run("@cf/meta/llama-3.3-70b-instruct-fp8-fast",{messages:[{role:"system",content:"Return only valid JSON."},{role:"user",content:prompt}],max_tokens:1800});
      let text=String(result?.response||"").trim().replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/i,"");
      const a=text.indexOf("{"),b=text.lastIndexOf("}");if(a>=0&&b>a)text=text.slice(a,b+1);
      return json({result:JSON.parse(text),provider:"Workers AI"});
    }
    return json({error:"No synthesis engine is available."},503);
  }catch(error){return json({error:String(error?.message||error).slice(0,500)},500)}
}

const TEAM_CLIENT = String.raw`(()=>{
const $=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)],E=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const STORE='unit369-team-sessions-v3',CUR='unit369-team-current-v3';
const ROLES={claude:{name:'Claude',role:'Strategic analyst',system:'You are the strategic analyst in the Unit369 AI team. Identify goals, constraints, tradeoffs, second-order effects and the strongest strategy. Be concrete. Answer in the user language.'},openai:{name:'ChatGPT',role:'Builder',system:'You are the builder and problem solver in the Unit369 AI team. Turn the question into an executable solution, steps, architecture or decision. Be practical and precise. Answer in the user language.'},grok:{name:'Grok',role:'Challenger',system:'You are the challenger in the Unit369 AI team. Stress-test assumptions, find blind spots, counterarguments, edge cases and missing evidence. Be useful, not contrarian for its own sake. Answer in the user language.'},workers:{name:'Workers AI',role:'Verifier',system:'You are the independent verifier in the Unit369 AI team. Check logic, simplify complexity, identify unsupported claims and give a neutral alternative view. Answer in the user language.'}};
let sessions=[],current=null,status={},running=false;
function load(){try{sessions=JSON.parse(localStorage.getItem(STORE)||'[]')}catch{sessions=[]}const id=localStorage.getItem(CUR);current=sessions.find(x=>x.id===id)||sessions[0]||null}
function persist(){localStorage.setItem(STORE,JSON.stringify(sessions.slice(0,40)));if(current)localStorage.setItem(CUR,current.id);else localStorage.removeItem(CUR)}
function fresh(){current={id:'s'+Date.now()+Math.random().toString(36).slice(2,7),title:'',createdAt:Date.now(),updatedAt:Date.now(),turns:[]};sessions.unshift(current);persist();renderSession();clearPanels()}
function clearPanels(){const p=$('#panels');if(p)p.innerHTML='';const q=$('#prompt');if(q)q.value=''}
function latest(){return current?.turns?.[current.turns.length-1]||null}
function historyFor(provider){const out=[];(current?.turns||[]).slice(-6).forEach(t=>{out.push({role:'user',content:t.q});if(t.answers?.[provider])out.push({role:'assistant',content:t.answers[provider]})});return out}
async function ask(provider,q){const role=ROLES[provider];const messages=[{role:'system',content:role.system},...historyFor(provider),{role:'user',content:q}];const url=provider==='workers'?'/api/free-ai':'/api/ai-proxy';const body=provider==='workers'?{messages}:{provider,messages,max_tokens:1600};const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok||d.error)throw Error(d.error||'AI request failed');return d.content||''}
function providerOn(p){const i=status.integrations||{};return p==='workers'?!!i.workersAi:!!i[p]}
function roleStrip(){const team=$('#page-team');if(!team||$('#team-roles'))return;const r=document.createElement('div');r.id='team-roles';r.className='role-strip';r.innerHTML=Object.entries(ROLES).map(([k,v])=>'<div class="role-chip"><div class="role-name">'+E(v.name)+'</div><div class="role-desc">'+E(v.role)+'</div></div>').join('');const anchor=$('#u369bar')||team.querySelector('.section-sub');anchor?.after(r)}
function sessionUi(){const team=$('#page-team');if(!team||$('#team-sessionbar'))return;const bar=document.createElement('div');bar.id='team-sessionbar';bar.className='team-sessionbar';bar.innerHTML='<div id="team-session-title" class="team-session-title"></div><button id="team-new" class="team-mini">＋</button><button id="team-history" class="team-mini">☰</button>';const roles=$('#team-roles');(roles||team.querySelector('.section-sub'))?.after(bar);const d=document.createElement('div');d.id='team-drawer';d.className='team-drawer';bar.after(d);$('#team-new').onclick=fresh;$('#team-history').onclick=()=>{d.classList.toggle('open');renderDrawer()};renderSession()}
function renderSession(){const e=$('#team-session-title');if(e)e.textContent=current?(current.title||'New session'):'New session'}
function renderDrawer(){const d=$('#team-drawer');if(!d)return;if(!sessions.length){d.innerHTML='<div class="team-empty">No sessions</div>';return}d.innerHTML=sessions.map(s=>'<div class="team-session"><div class="team-session-main"><div class="team-session-q">'+E(s.title||'New session')+'</div><div class="team-session-meta">'+new Date(s.updatedAt||s.createdAt).toLocaleString()+' · '+(s.turns?.length||0)+'</div></div><button class="team-mini" data-open="'+s.id+'">Open</button><button class="team-mini" data-del="'+s.id+'">×</button></div>').join('');d.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{current=sessions.find(x=>x.id===b.dataset.open)||current;persist();renderSession();restoreCurrent();d.classList.remove('open')});d.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{sessions=sessions.filter(x=>x.id!==b.dataset.del);if(current?.id===b.dataset.del)current=sessions[0]||null;persist();renderSession();renderDrawer();restoreCurrent()})}
function card(p){const r=ROLES[p],on=providerOn(p);return '<div class="panel" data-team-p="'+p+'"><div class="panel-head">'+E(r.name)+'<span class="provider-state '+(on?'':'off')+'">'+(on?'ON':'OFF')+'</span></div><div class="roleline">'+E(r.role)+'</div><div class="panel-body '+(on?'loading':'err')+'">'+(on?'working...':'Not connected')+'</div><div class="pa"><button class="ub" data-copy="'+p+'">Copy</button><button class="ub" data-follow="'+p+'">Continue</button></div></div>'}
function wireCards(){all('[data-copy]').forEach(b=>b.onclick=()=>{const t=$('[data-team-p="'+b.dataset.copy+'"] .panel-body')?.textContent||'';navigator.clipboard?.writeText(t)});all('[data-follow]').forEach(b=>b.onclick=()=>{const q=$('#prompt');if(q){q.value='Continue specifically with '+ROLES[b.dataset.follow].name+': ';q.focus()}})}
function drawTurn(t){const box=$('#panels');if(!box)return;box.innerHTML=Object.keys(ROLES).map(card).join('');Object.keys(ROLES).forEach(p=>{const e=$('[data-team-p="'+p+'"] .panel-body');if(!e)return;if(t.answers?.[p]){e.className='panel-body';e.textContent=t.answers[p]}else if(t.errors?.[p]){e.className='panel-body err';e.textContent=t.errors[p]}else if(!providerOn(p)){e.className='panel-body err';e.textContent='Not connected'}});wireCards();if(t.synthesis)renderSynthesis(t.synthesis)}
function restoreCurrent(){const t=latest();t?drawTurn(t):clearPanels()}
async function run(){if(running)return;const q=$('#prompt')?.value.trim();if(!q)return;if(!current)fresh();running=true;const btn=$('#sendBtn');if(btn)btn.disabled=true;const box=$('#panels');box.innerHTML=Object.keys(ROLES).map(card).join('');const turn={q,at:Date.now(),answers:{},errors:{},synthesis:null};const active=Object.keys(ROLES).filter(providerOn);await Promise.all(active.map(async p=>{const e=$('[data-team-p="'+p+'"] .panel-body');try{const a=await ask(p,q);turn.answers[p]=a;e.className='panel-body';e.textContent=a}catch(err){turn.errors[p]=err.message;e.className='panel-body err';e.textContent=err.message}}));current.turns.push(turn);if(!current.title)current.title=q.slice(0,80);current.updatedAt=Date.now();sessions=[current,...sessions.filter(s=>s.id!==current.id)];persist();renderSession();wireCards();if(btn)btn.disabled=false;running=false;const mode=$('.mode.active')?.dataset.mode;if(mode==='combine')await synth();if(mode==='critique')await synth(true)}
async function synth(critique=false){const t=latest();if(!t)return;const usable=Object.values(t.answers||{}).filter(Boolean);if(usable.length<2)return;let box=$('#panels'),f=$('#team-final');if(!f){f=document.createElement('div');f.id='team-final';f.className='team-final';box.appendChild(f)}f.innerHTML='<div class="team-final-head">Unit369 '+(critique?'Cross-check':'Final')+'</div><div class="team-final-body">Working...</div>';try{const r=await fetch('/api/team-synthesize',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({question:t.q,answers:t.answers,critique})}),d=await r.json();if(!r.ok||d.error)throw Error(d.error||'Synthesis failed');t.synthesis=d.result;current.updatedAt=Date.now();persist();renderSynthesis(d.result)}catch(e){f.querySelector('.team-final-body').textContent=e.message}}
function renderSynthesis(s){let f=$('#team-final');if(!f){f=document.createElement('div');f.id='team-final';f.className='team-final';$('#panels')?.appendChild(f)}const order=[['summary','Summary'],['consensus','Consensus'],['disagreements','Disagreements'],['risks','Risks'],['recommendation','Recommendation'],['next_steps','Next steps']];f.innerHTML='<div class="team-final-head">Unit369 Final</div><div class="team-final-body">'+order.map(([k,n])=>s?.[k]?'<div class="team-section"><h4>'+n+'</h4><div>'+E(s[k])+'</div></div>':'').join('')+'<div class="team-actions"><button class="ub" id="copy-final">Copy final</button></div></div>';$('#copy-final').onclick=()=>navigator.clipboard?.writeText(order.filter(([k])=>s?.[k]).map(([k,n])=>n+'\n'+s[k]).join('\n\n'))}
function takeover(){const old=$('#sendBtn');if(old){const n=old.cloneNode(true);old.replaceWith(n);n.addEventListener('click',e=>{e.preventDefault();run()})}const fb=$('#fb');if(fb)fb.onclick=()=>synth(false);const ns=$('#ns');if(ns)ns.onclick=fresh;const hb=$('#hb');if(hb)hb.onclick=()=>{$('#team-drawer')?.classList.toggle('open');renderDrawer()}}
async function boot(){load();try{status=await (await fetch('/api/status')).json()}catch{}if(!current)fresh();roleStrip();sessionUi();takeover();restoreCurrent()}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,120)):setTimeout(boot,120);
})();`;

export default {
  async fetch(request,env,ctx){
    const url=new URL(request.url);
    if(url.pathname==="/api/team-synthesize"&&request.method==="POST")return synthesize(request,env);
    if(url.pathname==="/ai-team.js")return new Response(TEAM_CLIENT,{headers:{"content-type":"application/javascript; charset=utf-8","cache-control":"no-store"}});
    const response=await app.fetch(request,env,ctx);const type=response.headers.get("content-type")||"";
    if(request.method==="GET"&&(url.pathname==="/"||url.pathname==="/app")&&type.includes("text/html")){
      const html=(await response.text()).replace(/<\/head>/i,TEAM_STYLE+'\n</head>').replace(/<\/body>/i,'<script src="/ai-team.js?v=1"></script></body>');
      const headers=new Headers(response.headers);headers.delete("content-length");headers.set("cache-control","no-store");
      return new Response(html,{status:response.status,statusText:response.statusText,headers});
    }
    return response;
  }
};