import app from "./theme.js";
const X=String.raw`
<style>
.u{display:flex;gap:8px;flex-wrap:wrap;margin:0 0 12px}.ub{border:1px solid #23405c;background:#0a1420;color:#77ceff;border-radius:10px;padding:8px 10px;font-size:11px;font-weight:700}.hist{display:none;border:1px solid #1d3045;border-radius:12px;padding:10px;margin-bottom:12px;background:#08111b}.hist.open{display:block}.hi{display:flex;gap:8px;padding:8px 0;border-bottom:1px solid #172638}.hi:last-child{border:0}.hit{flex:1;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;font-size:12px}.pa{display:flex;justify-content:flex-end;gap:6px;padding:0 12px 10px}.st{display:grid;grid-template-columns:1fr 1fr;gap:8px}.si{display:flex;justify-content:space-between;padding:10px;border:1px solid #1c2c40;border-radius:10px;background:#09111b;font-size:12px}.dot2{width:8px;height:8px;border-radius:50%;background:#ff667a}.dot2.ok{background:#4ed6a8}.sel{width:100%;background:#070c13;color:#fff;border:1px solid #202d40;border-radius:12px;padding:12px}.pv{display:none;border:1px solid #2a5b82;border-radius:12px;padding:12px;margin-top:12px;background:#091523}.pv.open{display:block}.pr{display:flex;justify-content:space-between;font-size:12px;padding:5px 0;border-bottom:1px solid #16263a}.plist{margin-top:12px;display:grid;gap:8px}.prow{display:flex;gap:9px;align-items:center;padding:9px;border:1px solid #18283a;border-radius:11px;background:#08101a}.pt{width:40px;height:40px;border-radius:8px;object-fit:cover;background:#101a27}.pm{flex:1;min-width:0}.pn{font-size:12px;font-weight:750;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.pmeta{font-size:10px;color:#6d8099}.badge{font-size:9px;color:#65caff;background:#10243a;border-radius:999px;padding:5px 7px}.toast{position:fixed;left:50%;bottom:95px;transform:translateX(-50%);z-index:999;background:#102033;color:#fff;border:1px solid #2c5279;border-radius:10px;padding:9px 12px;font-size:12px;display:none}.compact .page{padding-top:10px!important}.compact .mode{min-height:64px!important}
</style>
<script>
(()=>{const $=s=>document.querySelector(s),E=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));const K='u369h2',P='u369p2';let turns=[],answers={},armed=false,status={};
function toast(t){let x=$('.toast');if(!x){x=document.createElement('div');x.className='toast';document.body.appendChild(x)}x.textContent=t;x.style.display='block';clearTimeout(x._t);x._t=setTimeout(()=>x.style.display='none',1800)}
function load(k,d){try{return JSON.parse(localStorage.getItem(k)||'')||d}catch{return d}}function save(k,v){localStorage.setItem(k,JSON.stringify(v))}
function clean(){localStorage.removeItem('openaiKey');localStorage.removeItem('grokKey');['openaiKey','grokKey'].forEach(id=>{const e=$('#'+id);if(e)e.value='server'});const k=$('.keys');if(k&&k.querySelector('#openaiKey'))k.style.display='none'}
function toolbar(){const team=$('#page-team');if(!team||$('#u369bar'))return;const b=document.createElement('div');b.id='u369bar';b.className='u';b.innerHTML='<button class="ub" id="ns">＋ Nova sesija</button><button class="ub" id="hb">Istorija</button><button class="ub" id="fb">Finalni odgovor</button>';team.querySelector('.section-sub')?.after(b);const h=document.createElement('div');h.id='hist';h.className='hist';b.after(h);$('#ns').onclick=()=>{turns=[];answers={};$('#panels').innerHTML='';$('#prompt').value='';toast('Nova sesija')};$('#hb').onclick=()=>h.classList.toggle('open');$('#fb').onclick=final;renderHist()}
function renderHist(){const h=$('#hist');if(!h)return;const a=load(K,[]);h.innerHTML=a.length?a.map((x,i)=>'<div class="hi"><div class="hit">'+E(x.q)+'</div><button class="ub" data-i="'+i+'">Otvori</button></div>').join(''):'<small>Nema istorije.</small>';h.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{const x=a[+b.dataset.i];turns=x.t||[];answers=x.a||{};draw(x.a||{});h.classList.remove('open')})}
function msgs(p,q){const m=[{role:'system',content:'Ti si član Unit369 AI tima. Odgovori jasno, konkretno i na jeziku korisnika.'}];turns.slice(-5).forEach(t=>{m.push({role:'user',content:t.q});if(t.a?.[p])m.push({role:'assistant',content:t.a[p]})});m.push({role:'user',content:q});return m}
async function ask(p,q){const u=p==='workers'?'/api/free-ai':'/api/ai-proxy',body=p==='workers'?{messages:msgs(p,q)}:{provider:p,messages:msgs(p,q),max_tokens:1400};const r=await fetch(u,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok||d.error)throw Error(d.error||'AI greška');return d.content||''}
const prov=[['claude','Claude','#c9a15f'],['openai','ChatGPT','#52d7a5'],['grok','Grok','#b96fda'],['workers','Workers AI','#69a7ff']];function card(p,n,c){return '<div class="panel" data-p="'+p+'"><div class="panel-head" style="color:'+c+'">'+n+'</div><div class="panel-body loading">radi...</div><div class="pa"><button class="ub" data-c="'+p+'">Kopiraj</button><button class="ub" data-n="'+p+'">Nastavi</button></div></div>'}
function draw(a){const box=$('#panels');box.innerHTML=prov.map(x=>card(...x)).join('');prov.forEach(([p])=>{const e=box.querySelector('[data-p="'+p+'"] .panel-body');e.className='panel-body';e.textContent=a[p]||'(nema odgovora)'});wire()}
function wire(){document.querySelectorAll('[data-c]').forEach(b=>b.onclick=()=>{const t=$('[data-p="'+b.dataset.c+'"] .panel-body')?.textContent||'';navigator.clipboard?.writeText(t);toast('Kopirano')});document.querySelectorAll('[data-n]').forEach(b=>b.onclick=()=>{$('#prompt').value='Nastavi odgovor modela '+b.dataset.n+': ';$('#prompt').focus()})}
async function run(q){const box=$('#panels'),btn=$('#sendBtn');btn.disabled=true;box.innerHTML=prov.map(x=>card(...x)).join('');const a={};await Promise.all(prov.map(async([p])=>{const e=box.querySelector('[data-p="'+p+'"] .panel-body');try{a[p]=await ask(p,q);e.className='panel-body';e.textContent=a[p]}catch(x){e.className='panel-body err';e.textContent=x.message}}));turns.push({q,a});answers=a;const h=load(K,[]);h.unshift({q,t:turns.slice(-10),a});save(K,h.slice(0,15));renderHist();wire();btn.disabled=false;const mode=$('.mode.active')?.dataset.mode;if(mode==='combine')final();if(mode==='critique')critique(a)}
async function final(){const u=Object.entries(answers).filter(x=>x[1]);if(u.length<2)return toast('Potrebna su dva odgovora');const box=$('#panels');let c=$('#final');if(!c){c=document.createElement('div');c.id='final';c.className='panel';c.innerHTML='<div class="panel-head" style="color:#64cbff">Unit369 finalni odgovor</div><div class="panel-body loading">spajam...</div>';box.appendChild(c)}try{const t=await ask('claude','Spoji ove odgovore u jedan najbolji finalni odgovor, bez pominjanja modela:\n\n'+u.map(x=>x[0]+': '+x[1]).join('\n\n'));c.querySelector('.panel-body').className='panel-body';c.querySelector('.panel-body').textContent=t}catch(e){c.querySelector('.panel-body').textContent=e.message}}
async function critique(a){const u=Object.entries(a).filter(x=>x[1]);if(u.length<2)return;const c=document.createElement('div');c.className='panel';c.innerHTML='<div class="panel-head">Unakrsna kritika</div><div class="panel-body loading">analiziram...</div>';$('#panels').appendChild(c);try{const t=await ask('claude','Uporedi kritički ove odgovore i reci šta je najbolje:\n\n'+u.map(x=>x[0]+': '+x[1]).join('\n\n'));c.querySelector('.panel-body').className='panel-body';c.querySelector('.panel-body').textContent=t}catch(e){c.querySelector('.panel-body').textContent=e.message}}
document.addEventListener('click',e=>{if(!e.target.closest('#sendBtn'))return;e.preventDefault();e.stopImmediatePropagation();const q=$('#prompt').value.trim();q?run(q):toast('Unesi pitanje')},true);
function product(){const f=$('#page-product form');if(!f||$('#pex'))return;const x=document.createElement('div');x.id='pex';x.innerHTML='<label>Status</label><select name="status" class="sel"><option value="DRAFT">Draft — pregled pre objave</option><option value="ACTIVE">Objavi odmah</option></select><label>SKU osnova</label><input name="sku"><label>Tip proizvoda</label><input name="productType"><label>Vendor</label><input name="vendor"><label>Tagovi</label><input name="tags"><label>Slike</label><input type="file" name="images" accept="image/*" multiple>';f.insertBefore(x,f.querySelector('button[type=submit]'));f.querySelector('input[name=video]')?.removeAttribute('required');const p=document.createElement('div');p.id='pv';p.className='pv';f.appendChild(p);const l=document.createElement('div');l.innerHTML='<div class="workspace-label">Poslednji proizvodi</div><div id="plist" class="plist">Učitavanje...</div>';f.parentNode.appendChild(l);products()}
function preview(f){const d=new FormData(f),o={Naziv:d.get('title'),Cena:d.get('price'),Veličine:d.get('sizes'),Status:d.get('status'),SKU:d.get('sku')};$('#pv').innerHTML='<b>Pregled</b>'+Object.entries(o).map(x=>'<div class="pr"><span>'+E(x[0])+'</span><strong>'+E(x[1]||'—')+'</strong></div>').join('')+'<small>Klikni još jednom da potvrdiš.</small>';$('#pv').classList.add('open');armed=true;f.querySelector('button[type=submit]').textContent='Potvrdi i sačuvaj'}
async function submitP(f){const b=f.querySelector('button[type=submit]'),s=$('#pStatus');b.disabled=true;b.textContent='Čuvam...';try{const r=await fetch('/api/create-product',{method:'POST',body:new FormData(f)}),d=await r.json();if(!r.ok||d.error)throw Error(d.error||'Greška');s.className='ok';s.innerHTML='Sačuvano kao <b>'+E(d.product.status)+'</b>'+(d.adminUrl?' — <a target="_blank" href="'+d.adminUrl+'">otvori</a>':'');f.reset();$('#pv').classList.remove('open');armed=false;products();toast('Proizvod sačuvan')}catch(e){s.className='err';s.textContent=e.message}finally{b.disabled=false;b.textContent='Dodaj proizvod'}}
document.addEventListener('submit',e=>{const f=e.target.closest('#page-product form');if(!f)return;e.preventDefault();e.stopImmediatePropagation();armed?submitP(f):preview(f)},true);document.addEventListener('input',e=>{if(e.target.closest('#page-product form'))armed=false},true);
async function products(){const b=$('#plist');if(!b)return;try{const r=await fetch('/api/products'),d=await r.json();if(!r.ok||d.error)throw Error(d.error);b.innerHTML=(d.products||[]).slice(0,10).map(x=>'<div class="prow">'+(x.featuredMedia?.preview?.image?.url?'<img class="pt" src="'+E(x.featuredMedia.preview.image.url)+'">':'<div class="pt"></div>')+'<div class="pm"><div class="pn">'+E(x.title)+'</div><div class="pmeta">'+E(x.productType||x.vendor||'')+'</div></div><span class="badge">'+E(x.status)+'</span></div>').join('')}catch(e){b.textContent=e.message}}
async function settings(){try{status=await (await fetch('/api/status')).json()}catch{}const s=$('#page-settings');if(!s)return;const i=status.integrations||{},c=document.createElement('div');c.className='keys settings-card';c.innerHTML='<div class="settings-heading">Integracije</div><div class="st">'+[['claude','Claude'],['openai','OpenAI'],['grok','Grok'],['workersAi','Workers AI'],['shopify','Shopify']].map(x=>'<div class="si"><span>'+x[1]+'</span><span class="dot2 '+(i[x[0]]?'ok':'')+'"></span></div>').join('')+'</div><small>API ključevi su server-side Cloudflare secrets.</small>';s.insertBefore(c,s.children[2]||null);const pref=load(P,{compact:false}),d=document.createElement('div');d.className='keys settings-card';d.innerHTML='<div class="settings-heading">Aplikacija</div><div class="setting-row" id="compact"><span>Kompaktni prikaz</span><span>'+(pref.compact?'Uključen':'Isključen')+'</span></div><div class="setting-row"><span>Verzija</span><span>'+E(status.version||'—')+'</span></div><div class="setting-row" id="clearh"><span>Obriši AI istoriju</span><span>›</span></div>';s.appendChild(d);document.body.classList.toggle('compact',pref.compact);$('#compact').onclick=()=>{pref.compact=!pref.compact;save(P,pref);document.body.classList.toggle('compact',pref.compact);$('#compact span:last-child').textContent=pref.compact?'Uključen':'Isključen'};$('#clearh').onclick=()=>{localStorage.removeItem(K);renderHist();toast('Istorija obrisana')}}
function boot(){clean();toolbar();product();settings()}document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot):boot();})();
</script>`;
export default{async fetch(request,env,ctx){const r=await app.fetch(request,env,ctx),u=new URL(request.url),t=r.headers.get('content-type')||'';if(request.method==='GET'&&(u.pathname==='/'||u.pathname==='/app')&&t.includes('text/html')){const h=(await r.text()).replace(/<\/body>/i,X+'\n</body>'),hd=new Headers(r.headers);hd.delete('content-length');hd.set('cache-control','no-store');return new Response(h,{status:r.status,statusText:r.statusText,headers:hd})}return r}};