import app from "./enhancements.js";

const I18N = String.raw`
<script id="unit369-i18n">
(()=>{
const KEY='unit369-language';
const LANGS={sr:'Srpski',en:'English',it:'Italiano',de:'Deutsch'};
const T={
sr:{settings:'Settings',settingsSub:'Podešavanja Unit369 aplikacije.',aiTeam:'AI Tim',aiSub:'Postavi jedno pitanje i uporedi odgovore više AI modela.',products:'Proizvodi',productsSub:'Dodaj novi proizvod i upravljaj unosom na jednom mestu.',workMode:'Režim rada',side:'Jedan pored drugog',combine:'Spojeni odgovor',critique:'Unakrsna kritika',newQuestion:'Novo pitanje',placeholder:'Postavi pitanje svim modelima...',send:'Pošalji',answers:'Odgovori',newSession:'＋ Nova sesija',history:'Istorija',final:'Finalni odgovor',open:'Otvori',noHistory:'Nema istorije.',copy:'Kopiraj',continue:'Nastavi',working:'radi...',noAnswer:'(nema odgovora)',needTwo:'Potrebna su dva odgovora',finalTitle:'Unit369 finalni odgovor',merging:'spajam...',analysing:'analiziram...',enterQuestion:'Unesi pitanje',status:'Status',draft:'Draft — pregled pre objave',publish:'Objavi odmah',sku:'SKU osnova',productType:'Tip proizvoda',vendor:'Vendor',tags:'Tagovi',images:'Slike',latest:'Poslednji proizvodi',loading:'Učitavanje...',preview:'Pregled',name:'Naziv',price:'Cena',sizes:'Veličine',confirm:'Klikni još jednom da potvrdiš.',confirmSave:'Potvrdi i sačuvaj',saving:'Čuvam...',savedAs:'Sačuvano kao',view:'otvori',productSaved:'Proizvod sačuvan',addProduct:'Dodaj proizvod',integrations:'Integracije',serverSecrets:'API ključevi su server-side Cloudflare secrets.',app:'Aplikacija',compact:'Kompaktni prikaz',on:'Uključen',off:'Isključen',version:'Verzija',clearHistory:'Obriši AI istoriju',historyCleared:'Istorija obrisana',general:'Opšte',notifications:'Notifikacije',theme:'Tema',dark:'Tamna',language:'Jezik',about:'O aplikaciji',languageTitle:'Jezik aplikacije',languageSaved:'Jezik promenjen',productName:'Naziv proizvoda',description:'Opis',video:'Video'},
en:{settings:'Settings',settingsSub:'Unit369 application settings.',aiTeam:'AI Team',aiSub:'Ask one question and compare answers from multiple AI models.',products:'Products',productsSub:'Add new products and manage entries in one place.',workMode:'Work mode',side:'Side by side',combine:'Combined answer',critique:'Cross-critique',newQuestion:'New question',placeholder:'Ask all models a question...',send:'Send',answers:'Answers',newSession:'＋ New session',history:'History',final:'Final answer',open:'Open',noHistory:'No history yet.',copy:'Copy',continue:'Continue',working:'working...',noAnswer:'(no answer)',needTwo:'At least two answers are required',finalTitle:'Unit369 final answer',merging:'merging...',analysing:'analysing...',enterQuestion:'Enter a question',status:'Status',draft:'Draft — review before publishing',publish:'Publish now',sku:'SKU base',productType:'Product type',vendor:'Vendor',tags:'Tags',images:'Images',latest:'Latest products',loading:'Loading...',preview:'Preview',name:'Name',price:'Price',sizes:'Sizes',confirm:'Tap again to confirm.',confirmSave:'Confirm and save',saving:'Saving...',savedAs:'Saved as',view:'open',productSaved:'Product saved',addProduct:'Add product',integrations:'Integrations',serverSecrets:'API keys are stored as server-side Cloudflare secrets.',app:'Application',compact:'Compact view',on:'On',off:'Off',version:'Version',clearHistory:'Clear AI history',historyCleared:'History cleared',general:'General',notifications:'Notifications',theme:'Theme',dark:'Dark',language:'Language',about:'About',languageTitle:'Application language',languageSaved:'Language changed',productName:'Product name',description:'Description',video:'Video'},
it:{settings:'Impostazioni',settingsSub:'Impostazioni dell’app Unit369.',aiTeam:'Team AI',aiSub:'Fai una domanda e confronta le risposte di più modelli AI.',products:'Prodotti',productsSub:'Aggiungi nuovi prodotti e gestisci gli inserimenti in un unico posto.',workMode:'Modalità di lavoro',side:'Fianco a fianco',combine:'Risposta combinata',critique:'Critica incrociata',newQuestion:'Nuova domanda',placeholder:'Fai una domanda a tutti i modelli...',send:'Invia',answers:'Risposte',newSession:'＋ Nuova sessione',history:'Cronologia',final:'Risposta finale',open:'Apri',noHistory:'Nessuna cronologia.',copy:'Copia',continue:'Continua',working:'in corso...',noAnswer:'(nessuna risposta)',needTwo:'Servono almeno due risposte',finalTitle:'Risposta finale Unit369',merging:'unione...',analysing:'analisi...',enterQuestion:'Inserisci una domanda',status:'Stato',draft:'Bozza — controlla prima di pubblicare',publish:'Pubblica ora',sku:'Base SKU',productType:'Tipo di prodotto',vendor:'Vendor',tags:'Tag',images:'Immagini',latest:'Prodotti recenti',loading:'Caricamento...',preview:'Anteprima',name:'Nome',price:'Prezzo',sizes:'Taglie',confirm:'Tocca di nuovo per confermare.',confirmSave:'Conferma e salva',saving:'Salvataggio...',savedAs:'Salvato come',view:'apri',productSaved:'Prodotto salvato',addProduct:'Aggiungi prodotto',integrations:'Integrazioni',serverSecrets:'Le chiavi API sono segreti Cloudflare lato server.',app:'Applicazione',compact:'Vista compatta',on:'Attiva',off:'Disattiva',version:'Versione',clearHistory:'Cancella cronologia AI',historyCleared:'Cronologia cancellata',general:'Generale',notifications:'Notifiche',theme:'Tema',dark:'Scuro',language:'Lingua',about:'Info app',languageTitle:'Lingua dell’app',languageSaved:'Lingua cambiata',productName:'Nome prodotto',description:'Descrizione',video:'Video'},
de:{settings:'Einstellungen',settingsSub:'Einstellungen der Unit369-App.',aiTeam:'KI-Team',aiSub:'Stelle eine Frage und vergleiche Antworten mehrerer KI-Modelle.',products:'Produkte',productsSub:'Neue Produkte hinzufügen und Einträge an einem Ort verwalten.',workMode:'Arbeitsmodus',side:'Nebeneinander',combine:'Kombinierte Antwort',critique:'Kreuzkritik',newQuestion:'Neue Frage',placeholder:'Stelle allen Modellen eine Frage...',send:'Senden',answers:'Antworten',newSession:'＋ Neue Sitzung',history:'Verlauf',final:'Finale Antwort',open:'Öffnen',noHistory:'Noch kein Verlauf.',copy:'Kopieren',continue:'Fortsetzen',working:'läuft...',noAnswer:'(keine Antwort)',needTwo:'Mindestens zwei Antworten sind erforderlich',finalTitle:'Unit369 finale Antwort',merging:'zusammenführen...',analysing:'analysieren...',enterQuestion:'Frage eingeben',status:'Status',draft:'Entwurf — vor Veröffentlichung prüfen',publish:'Jetzt veröffentlichen',sku:'SKU-Basis',productType:'Produkttyp',vendor:'Anbieter',tags:'Tags',images:'Bilder',latest:'Neueste Produkte',loading:'Laden...',preview:'Vorschau',name:'Name',price:'Preis',sizes:'Größen',confirm:'Zum Bestätigen erneut tippen.',confirmSave:'Bestätigen und speichern',saving:'Speichern...',savedAs:'Gespeichert als',view:'öffnen',productSaved:'Produkt gespeichert',addProduct:'Produkt hinzufügen',integrations:'Integrationen',serverSecrets:'API-Schlüssel werden als serverseitige Cloudflare-Secrets gespeichert.',app:'Anwendung',compact:'Kompakte Ansicht',on:'Ein',off:'Aus',version:'Version',clearHistory:'KI-Verlauf löschen',historyCleared:'Verlauf gelöscht',general:'Allgemein',notifications:'Benachrichtigungen',theme:'Design',dark:'Dunkel',language:'Sprache',about:'Über die App',languageTitle:'App-Sprache',languageSaved:'Sprache geändert',productName:'Produktname',description:'Beschreibung',video:'Video'}};
let lang=localStorage.getItem(KEY)||'sr';if(!T[lang])lang='sr';
const t=k=>T[lang][k]||T.sr[k]||k;
function text(sel,val){const e=document.querySelector(sel);if(e)e.textContent=val}
function all(sel,fn){document.querySelectorAll(sel).forEach(fn)}
function labelByFor(name,val){const input=document.querySelector('[name="'+name+'"]');if(!input)return;const lab=input.previousElementSibling;if(lab&&lab.tagName==='LABEL')lab.textContent=val}
function apply(){document.documentElement.lang=lang;
 text('#page-team .section-title',t('aiTeam'));text('#page-team .section-sub',t('aiSub'));text('#page-product .section-title',t('products'));text('#page-product .section-sub',t('productsSub'));text('#page-settings .section-title',t('settings'));text('#page-settings .section-sub',t('settingsSub'));
 const ws=document.querySelectorAll('.workspace-label');if(ws[0])ws[0].textContent=t('workMode');if(ws[1])ws[1].textContent=t('newQuestion');if(ws[2])ws[2].textContent=t('answers');
 const modes=document.querySelectorAll('.mode');if(modes[0])modes[0].textContent=t('side');if(modes[1])modes[1].textContent=t('combine');if(modes[2])modes[2].textContent=t('critique');
 const p=document.querySelector('#prompt');if(p)p.placeholder=t('placeholder');text('#sendBtn',t('send'));
 const nav=document.querySelectorAll('nav.bottomnav .navitem');if(nav[0])nav[0].textContent=t('aiTeam');if(nav[1])nav[1].textContent=t('products');if(nav[2])nav[2].textContent=t('settings');
 text('#ns',t('newSession'));text('#hb',t('history'));text('#fb',t('final'));
 all('[data-c]',e=>e.textContent=t('copy'));all('[data-n]',e=>e.textContent=t('continue'));
 labelByFor('title',t('productName'));labelByFor('price',t('price'));labelByFor('sizes',t('sizes'));labelByFor('description',t('description'));labelByFor('video',t('video'));labelByFor('status',t('status'));labelByFor('sku',t('sku'));labelByFor('productType',t('productType'));labelByFor('vendor',t('vendor'));labelByFor('tags',t('tags'));labelByFor('images',t('images'));
 const st=document.querySelector('select[name="status"]');if(st&&st.options.length>1){st.options[0].textContent=t('draft');st.options[1].textContent=t('publish')}
 const pb=document.querySelector('#page-product button[type="submit"]');if(pb&&!/Čuvam|Saving|Salvataggio|Speichern/.test(pb.textContent))pb.textContent=t('addProduct');
 const heads=[...document.querySelectorAll('.settings-heading')];heads.forEach(h=>{const q=h.textContent.toLowerCase();if(q.includes('integr'))h.textContent=t('integrations');else if(q.includes('aplik')||q.includes('applic')||q.includes('anwendung'))h.textContent=t('app');else if(q.includes('opšte')||q.includes('general')||q.includes('generale')||q.includes('allgemein'))h.textContent=t('general')});
 const rows=[...document.querySelectorAll('#page-settings .setting-row')];rows.forEach(r=>{const a=r.querySelector('span:first-child'),b=r.querySelector('span:last-child');if(!a)return;const q=a.textContent.toLowerCase();if(q.includes('integr'))a.textContent=t('integrations');else if(q.includes('notifik')||q.includes('notif')||q.includes('benach'))a.textContent=t('notifications');else if(q==='tema'||q==='theme'||q==='design')a.textContent=t('theme');else if(q.includes('jezik')||q==='language'||q==='lingua'||q==='sprache')a.textContent=t('language');else if(q.includes('o aplik')||q.includes('about')||q.includes('info app')||q.includes('über'))a.textContent=t('about');else if(q.includes('kompakt')||q.includes('compact')||q.includes('vista compatta'))a.textContent=t('compact');else if(q.includes('verz')||q.includes('version'))a.textContent=t('version');else if(q.includes('obriši')||q.includes('clear ai')||q.includes('cancella')||q.includes('verlauf löschen'))a.textContent=t('clearHistory');if(b&&['Tamna','Dark','Scuro','Dunkel'].includes(b.textContent))b.textContent=t('dark')});
 ensureLanguage();
}
function ensureLanguage(){const s=document.querySelector('#page-settings');if(!s)return;let card=document.querySelector('#language-card');if(!card){card=document.createElement('div');card.id='language-card';card.className='keys settings-card';card.innerHTML='<div class="settings-heading" id="lang-head"></div><select id="lang-select" class="sel"></select>';const appCards=s.querySelectorAll('.settings-card');s.insertBefore(card,appCards[1]||null);const sel=card.querySelector('#lang-select');Object.entries(LANGS).forEach(([v,n])=>{const o=document.createElement('option');o.value=v;o.textContent=n;sel.appendChild(o)});sel.onchange=()=>{lang=sel.value;localStorage.setItem(KEY,lang);apply();showToast(t('languageSaved'))}}
 text('#lang-head',t('languageTitle'));const sel=document.querySelector('#lang-select');if(sel)sel.value=lang;
}
function showToast(msg){let x=document.querySelector('.toast');if(!x){x=document.createElement('div');x.className='toast';document.body.appendChild(x)}x.textContent=msg;x.style.display='block';clearTimeout(x._t);x._t=setTimeout(()=>x.style.display='none',1600)}
function translateDynamic(){apply();const hist=document.querySelector('#hist');if(hist&&hist.textContent.trim()==='Nema istorije.')hist.innerHTML='<small>'+t('noHistory')+'</small>';all('[data-i]',e=>e.textContent=t('open'));all('.panel-body.loading',e=>{if(['radi...','working...','in corso...','läuft...'].includes(e.textContent.trim()))e.textContent=t('working')});const latest=[...document.querySelectorAll('.workspace-label')].find(e=>/Poslednji proizvodi|Latest products|Prodotti recenti|Neueste Produkte/.test(e.textContent));if(latest)latest.textContent=t('latest')}
const mo=new MutationObserver(()=>{clearTimeout(mo._t);mo._t=setTimeout(translateDynamic,20)});function boot(){apply();mo.observe(document.body,{childList:true,subtree:true})}document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot):boot();
})();
</script>`;

export default {async fetch(request,env,ctx){const r=await app.fetch(request,env,ctx),u=new URL(request.url),type=r.headers.get('content-type')||'';if(request.method==='GET'&&(u.pathname==='/'||u.pathname==='/app')&&type.includes('text/html')){const h=(await r.text()).replace(/<\/body>/i,I18N+'\n</body>'),headers=new Headers(r.headers);headers.delete('content-length');headers.set('cache-control','no-store');return new Response(h,{status:r.status,statusText:r.statusText,headers})}return r}};