import app from "./settings-safe.js";

const STYLE=String.raw`<style id="u369-layout-safe-style">
html,body{max-width:100%;overflow-x:hidden}.page{min-width:0}.panel,.ss-card,.pws{min-width:0}button,input,textarea,select{max-width:100%}.u369-offline{display:none;position:fixed;left:12px;right:12px;top:max(10px,env(safe-area-inset-top));z-index:999;padding:9px 12px;border:1px solid #5b3d1e;border-radius:11px;background:#251a0b;color:#f2bd65;font-size:11px;text-align:center}.u369-offline.show{display:block}html[dir="rtl"] body{text-align:right}html[dir="rtl"] input:not([type="email"]):not([type="url"]),html[dir="rtl"] textarea,html[dir="rtl"] select{text-align:right;direction:rtl}html[dir="ltr"] input,html[dir="ltr"] textarea,html[dir="ltr"] select{direction:ltr}html.locale-long .u369-side-item,html.locale-long .u369-mode-btn{font-size:12px}@media(max-width:390px){html.locale-long .u369-side-item,html.locale-long .u369-mode-btn{line-height:1.25}}@media(prefers-reduced-motion:reduce){*,*:before,*:after{scroll-behavior:auto!important;animation-duration:.01ms!important;transition-duration:.01ms!important}}
</style>`;

const CLIENT=String.raw`(()=>{const LONG=new Set(['de','fi','hu','nl','pl','ru','uk','el','tr','cs','sk']);function adapt(){const tag=(document.documentElement.lang||navigator.language||'en').toLowerCase(),code=tag.split('-')[0];document.documentElement.classList.toggle('locale-long',LONG.has(code));document.body?.setAttribute('data-locale',tag);document.querySelectorAll('input[type="number"],input[inputmode="decimal"],input[type="url"],input[type="email"],input[name="sku"]').forEach(e=>e.dir='ltr')}function network(){let n=document.querySelector('.u369-offline');if(!n){n=document.createElement('div');n.className='u369-offline';n.setAttribute('data-i18n','offline');n.textContent='Offline — server actions are unavailable until connection returns.';document.body.appendChild(n)}n.classList.toggle('show',!navigator.onLine)}function boot(){adapt();network();window.addEventListener('online',network);window.addEventListener('offline',network);window.addEventListener('unit369-language-changed',adapt)}document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot):boot()})();`;

export default{async fetch(request,env,ctx){const r=await app.fetch(request,env,ctx);const u=new URL(request.url),t=r.headers.get('content-type')||'';if(request.method==='GET'&&(u.pathname==='/'||u.pathname==='/app')&&t.includes('text/html')){const html=(await r.text()).replace(/<\/head>/i,STYLE+'</head>').replace(/<\/body>/i,'<script>'+CLIENT+'</script></body>');const h=new Headers(r.headers);h.delete('content-length');h.set('cache-control','no-store');h.set('x-content-type-options','nosniff');h.set('referrer-policy','strict-origin-when-cross-origin');return new Response(html,{status:r.status,statusText:r.statusText,headers:h})}return r}};
