function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}})}
function id(prefix='n'){return prefix+'_'+crypto.randomUUID().replace(/-/g,'')}
function cleanName(v,max=160){return String(v||'').trim().slice(0,max)}
function safeKey(v){const s=String(v||'');return /^[A-Za-z0-9._:-]{1,160}$/.test(s)?s:''}
export class NativeStore{
  constructor(state){this.state=state;this.sql=state.storage.sql;this.sql.exec(`CREATE TABLE IF NOT EXISTS native_items (kind TEXT NOT NULL, id TEXT NOT NULL, parent_id TEXT NOT NULL DEFAULT '', name TEXT NOT NULL DEFAULT '', mime TEXT NOT NULL DEFAULT '', body TEXT NOT NULL DEFAULT '', meta TEXT NOT NULL DEFAULT '{}', created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, PRIMARY KEY(kind,id)); CREATE INDEX IF NOT EXISTS idx_native_kind_parent ON native_items(kind,parent_id); CREATE INDEX IF NOT EXISTS idx_native_kind_updated ON native_items(kind,updated_at DESC);`)}
  rows(cursor){return Array.from(cursor||[])}
  get(kind,itemId){return this.rows(this.sql.exec('SELECT * FROM native_items WHERE kind=? AND id=? LIMIT 1',kind,itemId))[0]||null}
  async fetch(request){const u=new URL(request.url),p=u.pathname.split('/').filter(Boolean);try{
    if(p[0]!=='native-store')return json({error:'Not found.'},404);
    if(p[1]==='files')return this.files(request,u,p.slice(2));
    if(p[1]==='data')return this.data(request,u,p.slice(2));
    return json({error:'Not found.'},404);
  }catch(e){return json({error:String(e.message||e)},500)}}
  async files(request,u,p){const now=Date.now();if(request.method==='POST'&&p.length===0){const b=await request.json(),name=cleanName(b.name);if(!name)return json({error:'File name is required.'},400);const itemId=id('f'),body=String(b.content??''),mime=cleanName(b.mime||'text/plain',100),parent=safeKey(b.parent_id),meta=JSON.stringify(b.meta&&typeof b.meta==='object'?b.meta:{});this.sql.exec('INSERT INTO native_items(kind,id,parent_id,name,mime,body,meta,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)','file',itemId,parent,name,mime,body,meta,now,now);return json({file:{id:itemId,name,mime,parent_id:parent,size:new TextEncoder().encode(body).length,created_at:now,updated_at:now}},201)}
    if(request.method==='GET'&&p.length===0){const parent=safeKey(u.searchParams.get('parent_id')),q=String(u.searchParams.get('q')||'').trim().slice(0,100);let r=q?this.rows(this.sql.exec('SELECT id,parent_id,name,mime,length(body) size,created_at,updated_at FROM native_items WHERE kind=? AND parent_id=? AND name LIKE ? ORDER BY updated_at DESC LIMIT 200','file',parent,'%'+q+'%')):this.rows(this.sql.exec('SELECT id,parent_id,name,mime,length(body) size,created_at,updated_at FROM native_items WHERE kind=? AND parent_id=? ORDER BY updated_at DESC LIMIT 200','file',parent));return json({files:r})}
    const itemId=safeKey(p[0]);if(!itemId)return json({error:'Invalid file id.'},400);const r=this.get('file',itemId);if(!r)return json({error:'File not found.'},404);if(request.method==='GET')return json({file:{...r,meta:JSON.parse(r.meta||'{}')}});if(request.method==='PUT'){const b=await request.json(),name=cleanName(b.name||r.name),body=b.content===undefined?r.body:String(b.content),mime=cleanName(b.mime||r.mime,100),parent=b.parent_id===undefined?r.parent_id:safeKey(b.parent_id),meta=b.meta===undefined?r.meta:JSON.stringify(b.meta&&typeof b.meta==='object'?b.meta:{});this.sql.exec('UPDATE native_items SET parent_id=?,name=?,mime=?,body=?,meta=?,updated_at=? WHERE kind=? AND id=?',parent,name,mime,body,meta,now,'file',itemId);return json({ok:true,id:itemId,updated_at:now})}if(request.method==='DELETE'){this.sql.exec('DELETE FROM native_items WHERE kind=? AND id=?','file',itemId);return json({ok:true})}return json({error:'Method not allowed.'},405)}
  async data(request,u,p){const now=Date.now();if(p[0]==='collections'&&p.length===1&&request.method==='POST'){const b=await request.json(),name=cleanName(b.name);if(!name)return json({error:'Collection name is required.'},400);const cid=id('c'),schema=JSON.stringify(b.schema&&typeof b.schema==='object'?b.schema:{});this.sql.exec('INSERT INTO native_items(kind,id,name,body,created_at,updated_at) VALUES(?,?,?,?,?,?)','collection',cid,name,schema,now,now);return json({collection:{id:cid,name,schema:JSON.parse(schema),created_at:now}},201)}
    if(p[0]==='collections'&&p.length===1&&request.method==='GET'){const r=this.rows(this.sql.exec('SELECT id,name,body schema,created_at,updated_at FROM native_items WHERE kind=? ORDER BY updated_at DESC LIMIT 200','collection')).map(x=>({...x,schema:JSON.parse(x.schema||'{}')}));return json({collections:r})}
    const cid=safeKey(p[1]);if(p[0]!=='collections'||!cid)return json({error:'Invalid collection.'},400);const col=this.get('collection',cid);if(!col)return json({error:'Collection not found.'},404);if(p[2]==='records'&&p.length===3&&request.method==='POST'){const b=await request.json(),rid=id('r'),record=b.record&&typeof b.record==='object'?b.record:{};this.sql.exec('INSERT INTO native_items(kind,id,parent_id,name,body,created_at,updated_at) VALUES(?,?,?,?,?,?,?)','record',rid,cid,cleanName(b.name||rid),JSON.stringify(record),now,now);return json({record:{id:rid,collection_id:cid,data:record,created_at:now}},201)}
    if(p[2]==='records'&&p.length===3&&request.method==='GET'){const q=String(u.searchParams.get('q')||'').trim().slice(0,100),rows=q?this.rows(this.sql.exec('SELECT id,name,body,created_at,updated_at FROM native_items WHERE kind=? AND parent_id=? AND (name LIKE ? OR body LIKE ?) ORDER BY updated_at DESC LIMIT 200','record',cid,'%'+q+'%','%'+q+'%')):this.rows(this.sql.exec('SELECT id,name,body,created_at,updated_at FROM native_items WHERE kind=? AND parent_id=? ORDER BY updated_at DESC LIMIT 200','record',cid));return json({records:rows.map(x=>({id:x.id,name:x.name,data:JSON.parse(x.body||'{}'),created_at:x.created_at,updated_at:x.updated_at}))})}
    const rid=safeKey(p[3]);if(p[2]!=='records'||!rid)return json({error:'Invalid record.'},400);const r=this.get('record',rid);if(!r||r.parent_id!==cid)return json({error:'Record not found.'},404);if(request.method==='GET')return json({record:{id:r.id,name:r.name,collection_id:cid,data:JSON.parse(r.body||'{}'),created_at:r.created_at,updated_at:r.updated_at}});if(request.method==='PUT'){const b=await request.json(),data=b.record&&typeof b.record==='object'?b.record:JSON.parse(r.body||'{}');this.sql.exec('UPDATE native_items SET name=?,body=?,updated_at=? WHERE kind=? AND id=?',cleanName(b.name||r.name),JSON.stringify(data),now,'record',rid);return json({ok:true,id:rid,updated_at:now})}if(request.method==='DELETE'){this.sql.exec('DELETE FROM native_items WHERE kind=? AND id=?','record',rid);return json({ok:true})}return json({error:'Method not allowed.'},405)}
}
