import { resolveAccount } from "./accounts.js";

const enc = new TextEncoder();
const dec = new TextDecoder();

const TOOLS = {
  anthropic:{name:'Anthropic (Claude API)',description:'Claude models via Messages API.',auth_type:'bearer',base_url:'https://api.anthropic.com/v1',extra_headers:{'anthropic-version':'2023-06-01'}},
  openai:{name:'OpenAI',description:'GPT models and OpenAI APIs.',auth_type:'bearer',base_url:'https://api.openai.com/v1',extra_headers:{}},
  xai:{name:'xAI (Grok)',description:'Grok models via xAI API.',auth_type:'bearer',base_url:'https://api.x.ai/v1',extra_headers:{}},
  github:{name:'GitHub',description:'Repositories, issues, pull requests and Actions.',auth_type:'bearer',base_url:'https://api.github.com',extra_headers:{Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28'},oauth:{authorize_url:'https://github.com/login/oauth/authorize',token_url:'https://github.com/login/oauth/access_token',client_id_env:'GITHUB_CLIENT_ID',client_secret_env:'GITHUB_CLIENT_SECRET',scope:'repo workflow read:user',format:'json'}},
  gitlab:{name:'GitLab',description:'Repositories, merge requests and CI/CD.',auth_type:'bearer',base_url:'https://gitlab.com/api/v4',extra_headers:{},oauth:{authorize_url:'https://gitlab.com/oauth/authorize',token_url:'https://gitlab.com/oauth/token',client_id_env:'GITLAB_CLIENT_ID',client_secret_env:'GITLAB_CLIENT_SECRET',scope:'api read_repository write_repository',format:'form'}},
  netlify:{name:'Netlify',description:'Sites, deploys and serverless functions.',auth_type:'bearer',base_url:'https://api.netlify.com/api/v1',extra_headers:{},oauth:{authorize_url:'https://app.netlify.com/authorize',token_url:'https://api.netlify.com/oauth/token',client_id_env:'NETLIFY_CLIENT_ID',client_secret_env:'NETLIFY_CLIENT_SECRET',scope:'',format:'form'}},
  vercel:{name:'Vercel',description:'Projects, deployments and edge functions.',auth_type:'bearer',base_url:'https://api.vercel.com',extra_headers:{},oauth:{authorize_url:'https://vercel.com/integrations/{slug}/new',token_url:'https://api.vercel.com/v2/oauth/access_token',client_id_env:'VERCEL_CLIENT_ID',client_secret_env:'VERCEL_CLIENT_SECRET',slug_env:'VERCEL_INTEGRATION_SLUG',scope:'',format:'json'}},
  cloudflare:{name:'Cloudflare',description:'Workers, Pages, R2 and DNS.',auth_type:'bearer',base_url:'https://api.cloudflare.com/client/v4',extra_headers:{}},
  shopify:{name:'Shopify',description:'Products, orders and store management.',auth_type:'shopify_token',base_url:null,extra_headers:{}},
  slack:{name:'Slack',description:'Channels, messages and notifications.',auth_type:'bearer',base_url:'https://slack.com/api',extra_headers:{},oauth:{authorize_url:'https://slack.com/oauth/v2/authorize',token_url:'https://slack.com/api/oauth.v2.access',client_id_env:'SLACK_CLIENT_ID',client_secret_env:'SLACK_CLIENT_SECRET',scope:'chat:write,channels:read',format:'form'}},
  discord:{name:'Discord',description:'Servers, bots, messages and webhooks.',auth_type:'bot_token',base_url:'https://discord.com/api/v10',extra_headers:{},oauth:{authorize_url:'https://discord.com/oauth2/authorize',token_url:'https://discord.com/api/oauth2/token',client_id_env:'DISCORD_CLIENT_ID',client_secret_env:'DISCORD_CLIENT_SECRET',scope:'identify webhook.incoming',format:'form'}},
  stripe:{name:'Stripe',description:'Payments, subscriptions and invoicing.',auth_type:'bearer',base_url:'https://api.stripe.com/v1',extra_headers:{}},
  supabase:{name:'Supabase',description:'Database, auth, storage and edge functions.',auth_type:'supabase',base_url:null,extra_headers:{}},
  firebase:{name:'Firebase',description:'Firestore, Auth and Firebase APIs.',auth_type:'bearer',base_url:'https://firestore.googleapis.com/v1',extra_headers:{},oauth:{authorize_url:'https://accounts.google.com/o/oauth2/v2/auth',token_url:'https://oauth2.googleapis.com/token',client_id_env:'GOOGLE_CLIENT_ID',client_secret_env:'GOOGLE_CLIENT_SECRET',scope:'https://www.googleapis.com/auth/firebase',format:'form',google:true}},
  google_drive:{name:'Google Drive',description:'Files and document storage.',auth_type:'bearer',base_url:'https://www.googleapis.com/drive/v3',extra_headers:{},oauth:{authorize_url:'https://accounts.google.com/o/oauth2/v2/auth',token_url:'https://oauth2.googleapis.com/token',client_id_env:'GOOGLE_CLIENT_ID',client_secret_env:'GOOGLE_CLIENT_SECRET',scope:'https://www.googleapis.com/auth/drive.file',format:'form',google:true}},
  notion:{name:'Notion',description:'Pages, databases and workspaces.',auth_type:'bearer',base_url:'https://api.notion.com/v1',extra_headers:{'Notion-Version':'2022-06-28'},oauth:{authorize_url:'https://api.notion.com/v1/oauth/authorize',token_url:'https://api.notion.com/v1/oauth/token',client_id_env:'NOTION_CLIENT_ID',client_secret_env:'NOTION_CLIENT_SECRET',scope:'',format:'notion'}}
};

function json(data,status=200,headers={}){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers}})}
function b64url(bytes){let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function fromB64url(s){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
async function shaKey(secret){if(!secret)throw new Error('ENCRYPTION_KEY is not configured.');return crypto.subtle.importKey('raw',await crypto.subtle.digest('SHA-256',enc.encode(secret)),'AES-GCM',false,['encrypt','decrypt'])}
async function encrypt(env,obj){const key=await shaKey(env.ENCRYPTION_KEY),iv=crypto.getRandomValues(new Uint8Array(12)),plain=enc.encode(JSON.stringify(obj)),cipher=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},key,plain)),all=new Uint8Array(iv.length+cipher.length);all.set(iv);all.set(cipher,iv.length);return b64url(all)}
async function decrypt(env,value){try{const all=fromB64url(value),key=await shaKey(env.ENCRYPTION_KEY),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:all.slice(0,12)},key,all.slice(12));return JSON.parse(dec.decode(plain))}catch{return null}}
async function hmac(env,text){if(!env.APP_SECRET)throw new Error('APP_SECRET is not configured.');const key=await crypto.subtle.importKey('raw',enc.encode(env.APP_SECRET),{name:'HMAC',hash:'SHA-256'},false,['sign']);return b64url(new Uint8Array(await crypto.subtle.sign('HMAC',key,enc.encode(text))))}
async function safeEqual(a,b){const aa=enc.encode(String(a)),bb=enc.encode(String(b));if(aa.length!==bb.length)return false;let n=0;for(let i=0;i<aa.length;i++)n|=aa[i]^bb[i];return n===0}
async function session(request,env){const account=await resolveAccount(request,env);return account?{sid:account.uid,account}:null}
function store(env,sid){if(!env.TOOL_STORE)throw new Error('TOOL_STORE binding is not configured.');return env.TOOL_STORE.get(env.TOOL_STORE.idFromName(sid))}
async function saveAuth(env,sid,toolId,auth){await store(env,sid).fetch('https://store/token/'+encodeURIComponent(toolId),{method:'PUT',body:await encrypt(env,auth)})}
async function loadAuth(env,sid,toolId){const r=await store(env,sid).fetch('https://store/token/'+encodeURIComponent(toolId));if(r.status===404)return null;return decrypt(env,await r.text())}
async function deleteAuth(env,sid,toolId){await store(env,sid).fetch('https://store/token/'+encodeURIComponent(toolId),{method:'DELETE'})}
function oauthAvailable(env,cfg){if(!cfg.oauth)return false;if(cfg.oauth.slug_env&&!env[cfg.oauth.slug_env])return false;return !!(env[cfg.oauth.client_id_env]&&env[cfg.oauth.client_secret_env])}
function sanitizeReturnTo(raw,origin){try{const u=new URL(raw||'/',origin);if(u.origin!==origin)return origin+'/';return u.toString()}catch{return origin+'/'}}
async function makeState(env,payload){const body=b64url(enc.encode(JSON.stringify(payload))),sig=await hmac(env,body);return `${body}.${sig}`}
async function parseState(env,state){const i=String(state||'').lastIndexOf('.');if(i<1)return null;const body=state.slice(0,i),sig=state.slice(i+1);if(!(await safeEqual(sig,await hmac(env,body))))return null;try{const p=JSON.parse(dec.decode(fromB64url(body)));if(!p.exp||Date.now()>p.exp)return null;return p}catch{return null}}
function authHeaders(cfg,a){const h={...cfg.extra_headers};if(cfg.auth_type==='bearer')h.Authorization=`Bearer ${a.access_token||a.api_key||a.token||''}`;if(cfg.auth_type==='bot_token')h.Authorization=`Bot ${a.bot_token||a.access_token||a.token||''}`;if(cfg.auth_type==='shopify_token')h['X-Shopify-Access-Token']=a.access_token||a.token||'';if(cfg.auth_type==='supabase'){h.apikey=a.api_key||'';h.Authorization=`Bearer ${a.api_key||''}`}return h}
function toolBase(id,cfg,input){if(id==='shopify'){const shop=String(input.shop_domain||'').toLowerCase();if(!/^[a-z0-9][a-z0-9-]*\.myshopify\.com$/.test(shop))throw new Error('A valid *.myshopify.com shop_domain is required.');return `https://${shop}/admin/api/2025-10`}if(id==='supabase'){const ref=String(input.project_ref||'').toLowerCase();if(!/^[a-z0-9-]{8,80}$/.test(ref))throw new Error('A valid Supabase project_ref is required.');return `https://${ref}.supabase.co/rest/v1`}return cfg.base_url}
async function execute(env,sid,input,allowWrite=false){const id=String(input.tool_id||''),cfg=TOOLS[id];if(!cfg)return{error:'Unknown tool.'};const method=String(input.method||'GET').toUpperCase();if(!['GET','POST','PUT','PATCH','DELETE'].includes(method))return{error:'Unsupported method.'};if(method!=='GET'&&!allowWrite)return{approval_required:true,message:'This action changes external data and requires explicit confirmation.',action:{tool_id:id,method,path:input.path,body:input.body||null,shop_domain:input.shop_domain||null,project_ref:input.project_ref||null}};const path=String(input.path||'');if(!path.startsWith('/')||path.startsWith('//')||path.includes('\\'))return{error:'Invalid API path.'};const auth=await loadAuth(env,sid,id);if(!auth)return{error:`${cfg.name} is not connected.`};let base;try{base=toolBase(id,cfg,input)}catch(e){return{error:e.message}}const h=authHeaders(cfg,auth);if(input.body!=null)h['content-type']=h['content-type']||'application/json';const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),15000);try{const r=await fetch(base+path,{method,headers:h,body:input.body!=null?JSON.stringify(input.body):undefined,signal:ctrl.signal});const text=await r.text();let data;try{data=JSON.parse(text)}catch{data=text.slice(0,12000)}return{status:r.status,ok:r.ok,data}}catch(e){return{error:e.name==='AbortError'?'API request timed out after 15 seconds.':String(e.message||e)}}finally{clearTimeout(timer)}}
function claudeTools(){return[{name:'execute_api_call',description:'Call one connected external service. GET calls may execute immediately. Mutating methods require explicit user approval.',input_schema:{type:'object',properties:{tool_id:{type:'string',enum:Object.keys(TOOLS)},method:{type:'string',enum:['GET','POST','PUT','PATCH','DELETE']},path:{type:'string'},shop_domain:{type:'string'},project_ref:{type:'string'},body:{type:'object'}},required:['tool_id','method','path']}}]}
async function agent(env,sid,message,history=[],allowWrite=false,language=''){if(!env.ANTHROPIC_API_KEY)return{error:'ANTHROPIC_API_KEY is not configured.'};const messages=[...history.slice(-12),{role:'user',content:String(message).slice(0,12000)}],tools=claudeTools();for(let turn=0;turn<6;turn++){const r=await fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'x-api-key':env.ANTHROPIC_API_KEY,'anthropic-version':'2023-06-01','content-type':'application/json'},body:JSON.stringify({model:env.ANTHROPIC_MODEL||'claude-sonnet-4-6',max_tokens:2048,system:`You are Unit369's tool orchestrator. Use connected tools only when needed. Reply naturally in the user's current language${language?` (${language})`:''}. Never claim an external action succeeded unless a tool result confirms it. Mutating actions require explicit confirmation; if a tool result says approval_required, explain exactly what will change and ask for confirmation.`,messages,tools})});const d=await r.json();if(!r.ok||d.error)return{error:d?.error?.message||'Claude orchestrator request failed.'};const uses=(d.content||[]).filter(x=>x.type==='tool_use');if(!uses.length)return{text:(d.content||[]).filter(x=>x.type==='text').map(x=>x.text).join('\n').trim(),history:[...messages,{role:'assistant',content:d.content}]};messages.push({role:'assistant',content:d.content});const results=[];for(const u of uses)results.push({type:'tool_result',tool_use_id:u.id,content:JSON.stringify(await execute(env,sid,u.input,allowWrite))});messages.push({role:'user',content:results})}return{error:'The orchestrator reached its step limit.'}}
async function oauthStart(request,env,url,s){const id=url.pathname.split('/').pop(),cfg=TOOLS[id];if(!cfg?.oauth)return json({error:'OAuth is not available for this tool.'},400);if(!oauthAvailable(env,cfg))return json({error:`OAuth credentials for ${cfg.name} are not configured.`},503);let authUrl=cfg.oauth.authorize_url;if(cfg.oauth.slug_env)authUrl=authUrl.replace('{slug}',encodeURIComponent(env[cfg.oauth.slug_env]));const callback=`${url.origin}/api/orchestrator/oauth/callback/${id}`,returnTo=sanitizeReturnTo(url.searchParams.get('return_to')||'/?connected='+id,url.origin),state=await makeState(env,{sid:s.sid,tool:id,returnTo,exp:Date.now()+10*60*1000,nonce:b64url(crypto.getRandomValues(new Uint8Array(12)))}),a=new URL(authUrl);a.searchParams.set('client_id',env[cfg.oauth.client_id_env]);a.searchParams.set('redirect_uri',callback);a.searchParams.set('state',state);if(cfg.oauth.scope)a.searchParams.set('scope',cfg.oauth.scope);a.searchParams.set('response_type','code');if(cfg.oauth.google){a.searchParams.set('access_type','offline');a.searchParams.set('prompt','consent')}return Response.redirect(a.toString(),302)}
async function exchangeOAuth(env,cfg,code,callback){const clientId=env[cfg.oauth.client_id_env],secret=env[cfg.oauth.client_secret_env],payload={client_id:clientId,client_secret:secret,code,redirect_uri:callback,grant_type:'authorization_code'};if(cfg.oauth.format==='notion'){const r=await fetch(cfg.oauth.token_url,{method:'POST',headers:{Authorization:'Basic '+btoa(`${clientId}:${secret}`),'content-type':'application/json','Notion-Version':'2022-06-28'},body:JSON.stringify({grant_type:'authorization_code',code,redirect_uri:callback})});return{r,d:await r.json()}}if(cfg.oauth.format==='form'){const r=await fetch(cfg.oauth.token_url,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded',Accept:'application/json'},body:new URLSearchParams(payload)});return{r,d:await r.json()}}const r=await fetch(cfg.oauth.token_url,{method:'POST',headers:{'content-type':'application/json',Accept:'application/json'},body:JSON.stringify(payload)});return{r,d:await r.json()}}
async function oauthCallback(env,url){const id=url.pathname.split('/').pop(),cfg=TOOLS[id],state=await parseState(env,url.searchParams.get('state'));if(!cfg?.oauth||!state||state.tool!==id)return json({error:'Invalid or expired OAuth state.'},400);const code=url.searchParams.get('code');if(!code)return json({error:url.searchParams.get('error')||'OAuth authorization was not completed.'},400);const callback=`${url.origin}/api/orchestrator/oauth/callback/${id}`,{r,d}=await exchangeOAuth(env,cfg,code,callback);if(!r.ok||d.error)return json({error:d.error_description||d.error||`Token exchange failed for ${cfg.name}.`},400);await saveAuth(env,state.sid,id,d);const back=sanitizeReturnTo(state.returnTo,url.origin),dest=new URL(back);dest.searchParams.set('connected',id);return Response.redirect(dest.toString(),302)}

export async function handleOrchestrator(request,env){const url=new URL(request.url);if(url.pathname.startsWith('/api/orchestrator/oauth/callback/'))return oauthCallback(env,url);if(url.pathname==='/api/orchestrator/health'){const a=await resolveAccount(request,env);return json({ok:true,storage:!!env.TOOL_STORE,authenticated:!!a,account_required:true})}let s;try{s=await session(request,env)}catch(e){return json({error:String(e.message||e)},503)}if(!s)return json({error:'Sign in to Unit369 to use connected tools.',login_url:'/account'},401);if(url.pathname.startsWith('/api/orchestrator/oauth/start/'))return oauthStart(request,env,url,s);if(url.pathname==='/api/orchestrator/tools'&&request.method==='GET'){try{const list=[];for(const[id,cfg]of Object.entries(TOOLS))list.push({id,name:cfg.name,description:cfg.description,connected:!!(await loadAuth(env,s.sid,id)),oauth_available:oauthAvailable(env,cfg),manual_available:true});return json({tools:list,user:{id:s.account.uid,email:s.account.email,name:s.account.name}})}catch(e){return json({error:String(e.message||e)},503)}}if(url.pathname==='/api/orchestrator/connect'&&request.method==='POST'){try{const b=await request.json();if(!TOOLS[b?.toolId]||!b?.auth||typeof b.auth!=='object')return json({error:'toolId and auth are required.'},400);await saveAuth(env,s.sid,b.toolId,b.auth);return json({ok:true,connected:b.toolId})}catch(e){return json({error:String(e.message||e)},500)}}if(url.pathname==='/api/orchestrator/disconnect'&&request.method==='POST'){try{const b=await request.json();if(!TOOLS[b?.toolId])return json({error:'Unknown tool.'},400);await deleteAuth(env,s.sid,b.toolId);return json({ok:true,disconnected:b.toolId})}catch(e){return json({error:String(e.message||e)},500)}}if(url.pathname==='/api/orchestrator/chat'&&request.method==='POST'){try{const b=await request.json();if(!b?.message)return json({error:'message is required.'},400);const out=await agent(env,s.sid,b.message,Array.isArray(b.history)?b.history:[],b.allowWrite===true,String(b.language||''));return json(out,out.error?500:200)}catch(e){return json({error:String(e.message||e)},500)}}return null}

export class ToolStore{
  constructor(state){this.state=state}
  async fetch(request){const u=new URL(request.url),id=decodeURIComponent(u.pathname.split('/').pop()||'');if(!id)return new Response('Bad request',{status:400});if(request.method==='GET'){const v=await this.state.storage.get('token:'+id);return v?new Response(v):new Response('',{status:404})}if(request.method==='PUT'){await this.state.storage.put('token:'+id,await request.text());return new Response('ok')}if(request.method==='DELETE'){await this.state.storage.delete('token:'+id);return new Response('ok')}return new Response('Method not allowed',{status:405})}
}