import app from "./settings-control.js";

const STYLE=String.raw`<style id="u369-production-polish">
:root{color-scheme:dark}html,body{max-width:100%;overflow-x:hidden}button,input,textarea,select{max-width:100%}button{touch-action:manipulation}.page{padding-bottom:112px!important}.panel-body{overflow-wrap:anywhere}.sendbtn,.pwf-btn,.sc-refresh,.ub,.team-mini{min-height:36px}.sendbtn:focus-visible,.pwf-btn:focus-visible,.sc-refresh:focus-visible,.ub:focus-visible,.team-mini:focus-visible,input:focus-visible,textarea:focus-visible,select:focus-visible{outline:2px solid #43b8ff!important;outline-offset:2px}.u369-health{position:fixed;right:12px;bottom:82px;z-index:80;width:10px;height:10px;border-radius:50%;background:#4ed6a8;box-shadow:0 0 12px rgba(78,214,168,.5);pointer-events:none}.u369-health.warn{background:#f1b45b;box-shadow:0 0 12px rgba(241,180,91,.5)}.u369-health.bad{background:#ff667a;box-shadow:0 0 12px rgba(255,102,122,.5)}.u369-offline{display:none;position:fixed;left:12px;right:12px;top:max(10px,env(safe-area-inset-top));z-index:999;padding:9px 12px;border:1px solid #5b3d1e;border-radius:11px;background:#251a0b;color:#f2bd65;font-size:11px;text-align:center}.u369-offline.show{display:block}header{padding-top:max(22px,calc(env(safe-area-inset-top) + 10px))!important}nav.bottomnav{padding-left:env(safe-area-inset-left)!important;padding-right:env(safe-area-inset-right)!important}.page,.panel,.keys,.pwf,.sc-card{min-width:0}.role-strip,.sc-grid,.modes{min-width:0}@media(max-width:360px){header{gap:12px!important}header:before{width:74px!important;height:74px!important;flex-basis:74px!important}h1{font-size:21px!important}.page{padding-left:14px!important;padding-right:14px!important}.u{gap:6px}.ub{padding-left:8px;padding-right:8px}}
@media(prefers-reduced-motion:reduce){*,*:before,*:after{scroll-behavior:auto!important;animation-duration:.01ms!important;transition-duration:.01ms!important}}
</style>`;

const CLIENT=String.raw`(()=>{const $=s=>document.querySelector(s);let failures=0;function mount(){if(!$('.u369-health')){const h=document.createElement('div');h.className='u369-health';h.setAttribute('aria-hidden','true');document.body.appendChild(h)}if(!$('.u369-offline')){const o=document.createElement('div');o.className='u369-offline';o.textContent='Offline — changes that require the server will wait until connection returns.';document.body.appendChild(o)}}function network(){mount();$('.u369-offline')?.classList.toggle('show',!navigator.onLine)}async function health(){mount();try{const r=await fetch('/api/status',{cache:'no-store'});if(!r.ok)throw Error('status');const d=await r.json(),i=d.integrations||{},n=Object.values(i).filter(Boolean).length;failures=0;const h=$('.u369-health');h.className='u369-health'+(n<2?' warn':'');h.title='Unit369 runtime OK · '+n+' integrations connected'}catch{failures++;const h=$('.u369-health');h.className='u369-health '+(failures>1?'bad':'warn');h.title='Unit369 status check failed'}}function cleanLegacy(){document.querySelectorAll('.eyebrow').forEach(e=>e.remove());const title=document.querySelector('header h1');if(title)title.textContent='Unit369';document.querySelectorAll('img').forEach(i=>{if(!i.alt)i.alt=''});const prompt=$('#prompt');if(prompt)prompt.setAttribute('aria-label','AI prompt');const send=$('#sendBtn');if(send)send.setAttribute('aria-label','Send to AI team')}function boot(){mount();network();cleanLegacy();health();window.addEventListener('online',()=>{network();health()});window.addEventListener('offline',network);setInterval(health,60000);const mo=new MutationObserver(()=>cleanLegacy());mo.observe(document.body,{childList:true,subtree:true})}document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot):boot()})();`;

export default{async fetch(request,env,ctx){const r=await app.fetch(request,env,ctx),u=new URL(request.url),t=r.headers.get('content-type')||'';if(request.method==='GET'&&(u.pathname==='/'||u.pathname==='/app')&&t.includes('text/html')){const html=(await r.text()).replace(/<\/head>/i,STYLE+'</head>').replace(/<\/body>/i,'<script>'+CLIENT+'</script></body>');const h=new Headers(r.headers);h.delete('content-length');h.set('cache-control','no-store');h.set('x-content-type-options','nosniff');h.set('referrer-policy','strict-origin-when-cross-origin');return new Response(html,{status:r.status,statusText:r.statusText,headers:h})}return r}};