import APP_HTML from "./app.html";

const APP_VERSION = "2026.08.23.2";

const UI_BASE = {
  chat:"Chat", products:"Products", settings:"Settings", newChat:"New chat", workspace:"Workspace",
  aiMode:"AI mode", providers:"Providers", chatHistory:"Chat history", sideBySide:"Side by side",
  combinedAnswer:"Combined answer", crossCritique:"Cross-critique", howHelp:"How can I help?",
  messageUnit369:"Message Unit369", send:"Send", copy:"Copy", thinking:"Thinking…", aiTeamDetails:"AI Team details",
  integrations:"Integrations", refresh:"Refresh", connected:"Connected", notConnected:"Not connected",
  application:"Application", applicationLanguage:"Application language", automatic:"Automatic", custom:"Custom",
  compactInterface:"Compact interface", aiModels:"AI models", serverDefault:"Server default", version:"Version",
  name:"Name", price:"Price", sizes:"Sizes", description:"Description", status:"Status", draft:"Draft", active:"Active",
  sku:"SKU", type:"Type", vendor:"Vendor", tags:"Tags", images:"Images", video:"Video", reviewProduct:"Review product",
  confirmSave:"Confirm & save", edit:"Edit", saving:"Saving…", productSaved:"Product saved.", finalPreview:"Final preview",
  productIntro:"Create and review products before saving.", settingsIntro:"Application, language and connection settings.",
  aiPrepareDraft:"AI prepare draft", preparing:"Preparing…", aiDraftPrepared:"AI draft prepared. Review every field before saving.",
  addProductFirst:"Add a product name or rough notes first.", requiredFields:"Name, valid price and at least one size are required.",
  publishImmediately:"This product will be published immediately. Continue?", noHistory:"No conversations yet.",
  noAnswer:"No answer available.", retry:"Try again", offline:"Offline — server actions are unavailable until connection returns.",
  resetPreferences:"Reset local preferences", modelsNote:"Optional external connections do not control Unit369 Core.",
  languageName:"Language name / BCP-47", productList:"Recent products", loadProducts:"Load products", emptyProducts:"No products found."
};

function json(data,status=200,extra={}){return new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store",...extra}})}
function safeError(error){return String(error?.message||error||"Unknown error").slice(0,700)}
function cleanJson(text){let t=String(text||"").trim().replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/i,"");const a=t.indexOf("{"),z=t.lastIndexOf("}");if(a>=0&&z>a)t=t.slice(a,z+1);return JSON.parse(t)}
function manifest(){return{id:"/",name:"Unit369",short_name:"Unit369",description:"AI workspace and product management.",start_url:"/",scope:"/",display:"standalone",background_color:"#05070c",theme_color:"#05070c",orientation:"portrait-primary",icons:[{src:"/app-icon-192.jpg?v="+APP_VERSION,sizes:"192x192",type:"image/png",purpose:"any maskable"},{src:"/app-icon-512.jpg?v="+APP_VERSION,sizes:"512x512",type:"image/png",purpose:"any maskable"}]}}
function serviceWorker(){return`const CACHE='unit369-${APP_VERSION}';\nconst CORE=['/manifest.json','/app-icon-192.jpg','/app-icon-512.jpg'];\nself.addEventListener('install',e=>{self.skipWaiting();e.waitUntil(caches.open(CACHE).then(c=>c.addAll(CORE)))});\nself.addEventListener('activate',e=>e.waitUntil((async()=>{for(const k of await caches.keys())if(k!==CACHE)await caches.delete(k);await self.clients.claim()})()));\nself.addEventListener('fetch',e=>{if(e.request.method!=='GET')return;const u=new URL(e.request.url);if(u.origin!==location.origin)return;e.respondWith((async()=>{try{return await fetch(e.request,{cache:'no-store'})}catch{return(await caches.match(e.request))||Response.error()}})())});`}
async function asset(env,path){if(!env.ASSETS)return new Response("Not Found",{status:404});return env.ASSETS.fetch(new Request("https://unit369.local"+path))}
async function freeAi(request,env){try{if(!env.AI)return json({error:"Unit369 AI is unavailable."},503);const incoming=await request.json();const messages=Array.isArray(incoming.messages)?incoming.messages:[];const result=await env.AI.run("@cf/meta/llama-3.3-70b-instruct-fp8-fast",{messages,max_tokens:1500});return json({provider:"unit369-core",model:"llama-3.3-70b",content:String(result?.response||"").trim()})}catch(e){return json({error:safeError(e)},500)}}
async function translateUi(request,env){try{const b=await request.json();const target=String(b.target||"en").trim();if(!target||target.toLowerCase().startsWith("en"))return json({d:UI_BASE});if(!env.AI)return json({d:UI_BASE});const prompt=`Translate every JSON value naturally into ${target} for a modern software application. Return ONLY valid JSON with exactly the same keys. Keep Unit369, API, AI, SKU and BCP-47 unchanged. Use the standard regional form of the selected language. For Serbian use natural standard Serbian, preferably Ekavian, and avoid Croatian-specific words such as Bok, tisuća, računalo and siječanj. JSON: ${JSON.stringify(UI_BASE)}`;const r=await env.AI.run("@cf/meta/llama-3.3-70b-instruct-fp8-fast",{messages:[{role:"system",content:"Return only valid JSON. Preserve every key exactly."},{role:"user",content:prompt}],max_tokens:3000});return json({d:{...UI_BASE,...cleanJson(r?.response)}})}catch(e){return json({d:UI_BASE,error:safeError(e)})}}
async function synthesize(request,env){try{if(!env.AI)return json({error:"Unit369 AI is unavailable."},503);const b=await request.json(),question=String(b.question||"").trim(),answers=b.answers&&typeof b.answers==="object"?b.answers:{},mode=String(b.mode||"combine"),language=String(b.language||"en"),usable=Object.entries(answers).filter(([,v])=>typeof v==="string"&&v.trim());if(!question||usable.length<2)return json({error:"At least two answers are required."},400);const instruction=mode==="critique"?"Critically compare the answers, identify disagreements and weaknesses, then give one best final answer.":"Combine the strongest parts of the answers into one direct final answer without mentioning the models.";const result=await env.AI.run("@cf/meta/llama-3.3-70b-instruct-fp8-fast",{messages:[{role:"system",content:`You are Unit369. ${instruction} Reply naturally in ${language}.`},{role:"user",content:`Question:\n${question}\n\nAnswers:\n${usable.map(([k,v])=>`[${k}]\n${v}`).join("\n\n")}`}],max_tokens:1800});return json({content:String(result?.response||"").trim()})}catch(e){return json({error:safeError(e)},500)}}
async function prepareProduct(request,env){try{if(!env.AI)return json({error:"Unit369 AI is unavailable."},503);const b=await request.json(),title=String(b.title||"").trim(),notes=String(b.notes||"").trim(),language=String(b.language||"en");if(!title&&!notes)return json({error:"Provide a product name or notes."},400);const prompt=`Return ONLY valid JSON with keys title, description, productType, tags, suggestedSizes, skuBase. tags and suggestedSizes must be arrays. Never invent material, origin, dimensions, certifications, stock or claims not supplied. Write in ${language}. Raw title: ${title}. Raw notes: ${notes}`;const r=await env.AI.run("@cf/meta/llama-3.3-70b-instruct-fp8-fast",{messages:[{role:"system",content:"You are the Unit369 ecommerce product assistant. Return only valid JSON and never fabricate facts."},{role:"user",content:prompt}],max_tokens:1400});const o=cleanJson(r?.response);return json({draft:{title:String(o.title||title),description:String(o.description||""),productType:String(o.productType||""),tags:Array.isArray(o.tags)?o.tags.map(String).slice(0,12):[],suggestedSizes:Array.isArray(o.suggestedSizes)?o.suggestedSizes.map(String).slice(0,20):[],skuBase:String(o.skuBase||"")}})}catch(e){return json({error:safeError(e)},500)}}
function integrationStatus(env){return{version:APP_VERSION,core:{native:true,ai:!!env.AI},external_connections:{claude:!!env.ANTHROPIC_API_KEY,openai:!!env.OPENAI_API_KEY,grok:!!(env.GROK_API_KEY||env.XAI_API_KEY),shopify:!!(env.SHOPIFY_SHOP&&env.SHOPIFY_CLIENT_ID&&env.SHOPIFY_CLIENT_SECRET)},integrations:{workersAi:!!env.AI}}}
function serveApp(){return new Response(APP_HTML,{headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store, no-cache, must-revalidate","pragma":"no-cache","x-content-type-options":"nosniff","referrer-policy":"strict-origin-when-cross-origin"}})}

export default{async fetch(request,env){const url=new URL(request.url);if((url.pathname==="/"||url.pathname==="/app")&&request.method==="GET")return serveApp();if(url.pathname==="/api/status"&&request.method==="GET")return json(integrationStatus(env));if(url.pathname==="/api/free-ai"&&request.method==="POST")return freeAi(request,env);if(url.pathname==="/api/ui-i18n"&&request.method==="POST")return translateUi(request,env);if(url.pathname==="/api/team-synthesize"&&request.method==="POST")return synthesize(request,env);if(url.pathname==="/api/product-prepare"&&request.method==="POST")return prepareProduct(request,env);if(url.pathname==="/manifest.json")return new Response(JSON.stringify(manifest()),{headers:{"content-type":"application/manifest+json; charset=utf-8","cache-control":"no-store"}});if(url.pathname==="/sw.js")return new Response(serviceWorker(),{headers:{"content-type":"application/javascript; charset=utf-8","cache-control":"no-store","service-worker-allowed":"/"}});if(url.pathname==="/app-icon-192.jpg")return asset(env,"/unit369-192.png");if(url.pathname==="/app-icon-512.jpg")return asset(env,"/unit369-512.png");if(env.ASSETS&&request.method==="GET"){const r=await env.ASSETS.fetch(request);if(r.status!==404)return r}return new Response("Not Found",{status:404})}};